### ISSUE TITLE
$0-save is not connected

### ISSUE THREAD

**Issue by worikgh** [jaffasplaffa/Pure-data-patches#1]
In `test.pd` the bang labeld `S` sends to `$0-save` that is not defined

**Comment by jaffasplaffa** [comment]
It's connected inside the param-savestate.pd abstraction, as supposed. It works as supposed.
<img width="482" alt="Screenshot 2022-03-30 at 08 46 16" src="https://user-images.githubusercontent.com/14827192/160768814-ac4b08b9-f46f-448e-b893-1e900ecc79fd.png">

$1 in t param-savestate.pd is $0 from the test.pd patch, see the notes at top of test.pd in the image above. I see it might be a bit confusing, but it works and it's really not ment to be edited too much, just trust that it works ;)
